### ISSUE TITLE
IDE suggestion

### ISSUE THREAD

**Issue by adamkumlin** [adamkumlin/minecraft-no-limit-redstone-mod#5]
after much deliberation, i switched from coding java in VS Code to [IntelliJ IDEA](https://www.jetbrains.com/idea/) (the community version, which is free. NOT the ultimate version which you have to pay for).

i feel like this IDE is specifically built for java development, it's way more intuitive in my opinion

just a suggestion 😊

**Comment by simon-s-99** [comment]
I've only ever tried Eclipse as an IDE for Java code but this sounds like a solid idea as IntelliJ is a lot prettier than Eclipse.

VS Code for Java sounds like a nightmare 😅
